fixed/nav
TomIA24/unow-front pull request #10
Opened 2024-09-18 09:00 UTC by AdemBenAbdallah

2024-09-19 08:34 UTC, TomIA24 requested changes

2024-09-19 08:34 UTC, TomIA24 commented on src/component/Personalize/index.jsx
in line 1026 (and in general) when we use states, variables the name shoud be in camelCase format

2024-09-19 20:48 UTC, elayeboussama requested changes

2024-09-19 20:48 UTC, elayeboussama commented on src/component/Nav/index.jsx
> +    console.log('close popup');
don't forget to remove console.log after testing

2024-09-19 20:48 UTC, elayeboussama commented on src/component/Nav/index.jsx
>      setpopupopen(false);
change it to setPopupOpen ( camel case naming for variables)

2024-09-19 20:48 UTC, elayeboussama commented on src/component/Nav/index.jsx
>                  {" "}
remove this

2024-09-20 12:41 UTC, Nesrine1333 commented on src/component/Personalize/index.jsx
Done.

2024-09-20 12:55 UTC, Nesrine1333 commented on src/component/Nav/index.jsx
>                  {" "}
Done

2024-09-20 16:02 UTC, merged