Routing/quiz course
TomIA24/unow-front pull request #11
Opened 2024-09-18 14:26 UTC by Nesrine1333

removed the go back button , I haven't finished it yet, there's no direct routre for the paid course 
changed the api form https://127.1... to the one with .env (quiz component)
signup shouldn't be double 
home footer the new one (the deployed one is the old )
the colose popup is still not stable

2024-09-19 09:41 UTC, TomIA24 requested changes

2024-09-19 09:41 UTC, TomIA24 commented on src/component/Quiz/nabar/index.jsx
> +{/* <div> <button onClick={handlehome}>Go Back</button></div> */}
this button did not handle any action, why ?

2024-09-19 20:52 UTC, elayeboussama requested changes

2024-09-19 20:52 UTC, elayeboussama commented on src/component/Course/index.jsx
> +    console.log('Course ID:', id);
don't forget to remove console.log after testing

2024-09-19 20:52 UTC, elayeboussama commented on src/component/Nav/index.jsx
> +        setcandidateData(candidateResponse.data);
change it to setCandidateData

2024-09-19 20:52 UTC, elayeboussama commented on src/component/Nav/index.jsx
> +    console.log('close popup');
don't forget to remove console.log after testing

2024-09-19 20:52 UTC, elayeboussama commented on src/component/Nav/index.jsx
>      setpopupopen(false);
change it to setPopupOpen

2024-09-19 20:52 UTC, elayeboussama commented on src/component/Nav/index.jsx
>                  {" "}
remove this

2024-09-19 20:52 UTC, elayeboussama commented on src/component/Personalize/index.jsx
> +      setcandidatdata(candidateResponse.data)
change this to setCandidateData

2024-09-19 20:52 UTC, elayeboussama commented on src/component/Quiz/Questions/index.jsx
> +                              className={styles.checkmarkcontainer}
camel case naming

2024-09-19 20:52 UTC, elayeboussama commented on src/component/Quiz/Questions/index.jsx
> +                              className={styles.rdiocontainer}
camel case naming

2024-09-19 20:52 UTC, elayeboussama commented on src/component/Quiz/Questions/index.jsx
> +                              <span className={styles.checkmark}></span>
camel case naming

2024-09-19 20:52 UTC, elayeboussama commented on src/component/Quiz/nabar/index.jsx
> +console.log("quizId",quizId);
don't forget to remove console.log after testing

2024-09-19 20:52 UTC, elayeboussama commented on src/component/Quiz/nabar/index.jsx
> +  console.log("quiz.courseID",quiz.courseID);
don't forget to remove console.log after testing

2024-09-19 20:52 UTC, elayeboussama commented on src/component/Quiz/nabar/styles.module.css
> +  .pdcontainer{
camel case naming

2024-09-19 20:52 UTC, elayeboussama commented on src/component/Quiz/nabar/styles.module.css
>    .imagebackground {
camel case naming

2024-09-19 20:52 UTC, elayeboussama commented on src/component/Quiz/nabar/styles.module.css
> +    padding-right: 13.5%; */
Remove unnecessary comments

2024-09-20 12:56 UTC, Nesrine1333 commented on src/component/Quiz/nabar/index.jsx
> +{/* <div> <button onClick={handlehome}>Go Back</button></div> */}
Done

2024-09-20 13:04 UTC, Nesrine1333 commented on src/component/Nav/index.jsx
>      setpopupopen(false);
done

2024-09-20 13:04 UTC, Nesrine1333 commented on src/component/Nav/index.jsx
>                  {" "}
Done

2024-09-20 13:08 UTC, Nesrine1333 commented on src/component/Quiz/nabar/styles.module.css
> +    padding-right: 13.5%; */
done

2024-09-20 13:20 UTC, Nesrine1333 commented on src/component/Nav/index.jsx
> +        setcandidateData(candidateResponse.data);
done

2024-09-20 16:35 UTC, merged