Fix/display courses training
TomIA24/unow-front pull request #13
Opened 2024-09-19 15:54 UTC by AdemBenAbdallah

**Fix Bugs and Responsiveness of The Category Details Page.**

1. **Dynamic Card Display Based on Categories and User Selection**:
   - Cards are now displayed based on the category the user selects (courses or training).
   
2. **Bug Fix: Training Page Refresh Issue**:
   - Resolved the issue where refreshing a training page redirected the user back to the courses page. Now, the page maintains its current state on refresh.

3. **ResourceCard Component Creation**:
   - Introduced a new `ResourceCard` component that represents both course and training cards for the home page.

4. **Breadcrumb Navigation**:
   - Implemented breadcrumb navigation (e.g., *Home > Categories > CategoryType*) to let users know which category they are in.
   - The displayed image dynamically changes based on the selected category.

5. **Card Navigation to Details Page**:
   - Clicking on a card now takes the user to the respective course or training details page.

6. **Responsive Card Layout**:
   - Made the cards responsive.

2024-09-19 20:22 UTC, TomIA24 requested changes

2024-09-19 20:22 UTC, TomIA24 commented on src/App.js
> +              path="/categoryCourses/:id/:categoryName/:contentType"
change the categoryCourses to just category if there is no other route with this name

2024-09-19 20:22 UTC, TomIA24 commented on src/component/GenericSwitcher/index.jsx
> +                props.selectedItem === item.title
don't forget here to use the destructed variables from props

2024-09-19 20:22 UTC, TomIA24 commented on src/component/GenericSwitcher/index.jsx
> +              onClick={() => props.setSelectedItem(item.title)}
here also use the destructed variable ( function in this case)

2024-09-19 20:22 UTC, TomIA24 commented on src/component/GenericSwitcher/index.jsx
> +              onClick={() => props.setSelectedItem(item.title)}
extract the logic in onClick prop to an external function, so we can add more business logic to this function in the future if we need that 
 onClick={()=>handleSelect(item.title)}
 const () => handleSelect(title) => { props.setSelectedItem(item.title)}

2024-09-19 20:22 UTC, TomIA24 commented on src/component/GenericSwitcher/index.jsx
> +              onClick={() => props.setSelectedItem(item.title)}
use id better than the title if you can

2024-09-19 20:22 UTC, TomIA24 commented on src/component/Home/Categories/CategoryDetails/CourseItem/index.jsx
> +
extract the logic of making the first letter capitalized into a shared function that we can reuse it

2024-09-19 20:22 UTC, TomIA24 commented on src/component/Home/Categories/CategoryDetails/CourseItem/index.jsx
> +                  marginTop: "16px",
extract inline style into a class and call it, for cleaner code

2024-09-19 20:22 UTC, TomIA24 commented on src/component/Home/Categories/CategoryDetails/CourseItem/index.jsx
> +                    },
extract inline style into a class and call it, for cleaner code, if this component didn't accept className prop, extract into a constant in an other file of styling (in the same folder of this component , for example style.js

2024-09-19 20:22 UTC, TomIA24 commented on src/component/Home/Categories/CategoryDetails/CourseItem/styles.module.css
> +  /* width: clamp(120px, 21vw, 180px); */
remove comment if you don't need it

2024-09-19 20:22 UTC, TomIA24 commented on src/component/Home/Categories/CategoryDetails/index.jsx
> +          <CourseItem key={course.id} course={course} />
i prefer here to add the courses to another list and use it here ( const [coursesDisplayed, setCoursesDisplayed] = useState(courses ? courses || [ ] )  )
it will help you in the future when you will implement the search

2024-09-19 20:22 UTC, TomIA24 commented on src/component/Home/Categories/CategoryDetails/index.jsx
> +            <Box sx={{ width: "200px", height: "200px" }}>
try not to use fixed sizes ( px ) it will make it harder in the responsive side

2024-09-19 20:22 UTC, TomIA24 commented on src/component/Home/Categories/CategoryDetails/index.jsx
> +          <Box sx={{ display: "flex", alignItems: "center", gap: "0.5rem" }}>
try to find a solution for inline styling

2024-09-19 20:22 UTC, TomIA24 commented on src/component/Nav/index.jsx
> -    //console.log(WindowWidth)
Remove unnecessary comments

2024-09-19 20:25 UTC, elayeboussama requested changes
All comments are negotiable

2024-09-20 08:47 UTC, AdemBenAbdallah commented on src/component/Admin/AddCourse/index.jsx
> +                      </button>
oakay

2024-09-20 08:53 UTC, AdemBenAbdallah commented on src/component/GenericSwitcher/index.jsx
> +        {props?.items.map((item, i) => {
okay

2024-09-20 09:36 UTC, AdemBenAbdallah commented on src/component/GenericSwitcher/index.jsx
> +              onClick={() => props.setSelectedItem(item.title)}
I don't want to create a function now because it's not needed. The code will be shorter and easier to understand. If we need more logic in the future, we can separate it into another function.

2024-09-20 09:37 UTC, AdemBenAbdallah commented on src/component/GenericSwitcher/index.jsx
> +              onClick={() => props.setSelectedItem(item.title)}
For the comparison with the ID, I get setSelectedItem from the category details, where it is used to compare strings like 'COURSES' or 'TRAININGS' to decide what to fetch. I can't store the ID in that state. I could create another state to hold the ID and pass it for comparison in GenericSwitch, but we don't need that—it would cause unnecessary re-renders and use memory without any real benefit

2024-09-20 13:44 UTC, AdemBenAbdallah commented on src/component/GenericSwitcher/index.jsx
> +  } = useParams();
The ID already exists in the URL, so there is no reason to create a hook to get it. We don't need that. This component is under CategoryDetails.

2024-09-20 13:51 UTC, AdemBenAbdallah commented on src/component/Home/Categories/CategoryDetails/index.jsx
> +          <CourseItem key={course.id} course={course} />
I didn’t understand this well. I’m not sure why creating another state would help with the search. As I understand it, for the search, we will just create a state for the search term, and the useEffect will trigger when the state changes. This will send the search term to the backend, where the filtering will happen. The filtering will be done by the backend, not on the frontend.

2024-09-20 15:53 UTC, elayeboussama approved these changes

2024-09-20 15:53 UTC, merged