fix bug scrolling
TomIA24/unow-front pull request #56
Opened 2024-10-16 21:03 UTC by KhRania

## What does this do?

fix bug scrolling in featured products

## Why did you do this?

fix bug scrolling in featured products

 

## Who/what does this impact?

User Experience

## How did you test this?

 
localhost  

## Add snapshots to the changes (if applicable)

2024-10-17 11:47 UTC, TomIA24 requested changes

2024-10-17 11:47 UTC, TomIA24 commented on src/component/Main/index.jsx
> +                  thumbnail="./images/home/right.png"
why changed this ?

2024-10-17 11:54 UTC, KhRania commented on src/component/Main/index.jsx
> +                  thumbnail="./images/home/right.png"
My bad filepath return a big on localhost so I changed with fix image

2024-10-17 13:34 UTC, elayeboussama commented on src/component/Main/index.jsx
> +                  thumbnail="./images/home/right.png"
Create a conditional check: if training.thumbnail.filepath exists, display it; otherwise, show a default image

2024-10-17 16:45 UTC, KhRania commented on src/component/Main/index.jsx
> +                  thumbnail="./images/home/right.png"
done

2024-10-18 05:32 UTC, elayeboussama approved these changes

2024-10-18 05:32 UTC, merged